print("hello M.6/14")
print("my name is ratthatee")
print("my surname is chaijan")
print("I'm 17 and gonna 18 in this June")
print("I study at chonrasadornumrung")
print("I leave in Sriracha")
print("My fav color is Red&Black")
print("My address is 99/108 Surasak Sriracha chonburi")
print("My fav food is Omu rice")
print("My fav subject is Physics")
print("I hate Biology")
#ชื่อ รัฐธีร์ ชัยจันทร์ เลขที่ 32 